Main: Clase_A.o Clase_B.o Clase_C.o Main.o
	g++ Clase_A.o Clase_B.o Clase_C.o Main.o -o Main   
Clase_A.o: Clase_A.h Clase_A.cc
	g++ -c Clase_A.cc
Clase_B.o: Clase_B.h Clase_B.cc
	g++ -c Clase_B.cc
Clase_C.o: Clase_C.h Clase_C.cc
	g++ -c Clase_C.cc

Main.o: Main.cc
	g++ -c Main.cc
